// ============================================================
// Bord Codegen — Next.js App Router output
// ============================================================

import {
  BordFile, ComponentNode,
  PropsBlock, StateBlock, ServerBlock, ClientBlock,
  FieldDecl, TypeExpr, ClientFunction, Expr,
} from "../parser/ast";

export type GeneratedFiles = {
  "page.tsx":   string;
  "client.tsx": string;
  "types.ts":   string;
};

export class NextjsCodegen {
  generate(file: BordFile): GeneratedFiles {
    return {
      "page.tsx":   this.genPage(file),
      "client.tsx": this.genClient(file),
      "types.ts":   this.genTypes(file),
    };
  }

  // ------------------------------------------------------------------ page.tsx

  private genPage(file: BordFile): string {
    const { component: c } = file;
    const clientImport = `./${c.name}.client`;

    const serverLines = (c.server?.assignments ?? []).map(a => {
      const val = a.value.kind === "AwaitExpr"
        ? `await ${a.value.expression}`
        : exprToString(a.value);
      return `  const ${a.name} = ${val};`;
    });

    const passServerProps = (c.server?.assignments ?? [])
      .map(a => `      ${a.name}={${a.name}}`).join("\n");

    const passProps = (c.props?.fields ?? [])
      .map(f => `      ${f.name}={${f.name}}`).join("\n");

    const pageArg = c.props
      ? `props: ${c.name}Props`
      : "";

    const destructure = c.props && c.props.fields.length > 0
      ? `  const { ${c.props.fields.map(f => f.name).join(", ")} } = props;`
      : "";

    return `// Generated by Bord v0.1 — do not edit
import type { ${c.name}Props } from "./types";
import { ${c.name}Client } from "${clientImport}";

export default async function Page(${pageArg}) {
${destructure}
${serverLines.join("\n")}
  return (
    <${c.name}Client
${passServerProps}${passProps}
    />
  );
}
`.replace(/\n{3,}/g, "\n\n");
  }

  // ------------------------------------------------------------------ client.tsx

  private genClient(file: BordFile): string {
    const { component: c } = file;

    // Build the props type for the client component
    const serverFields = (c.server?.assignments ?? []).map(a => {
      const t = a.typeAnnotation ? this.typeToTs(a.typeAnnotation) : "unknown";
      return `  ${a.name}: ${t};`;
    });
    const propsFields = (c.props?.fields ?? []).map(f => {
      const t = f.typeAnnotation ? this.typeToTs(f.typeAnnotation) : "unknown";
      const opt = f.defaultValue !== null ? "?" : "";
      return `  ${f.name}${opt}: ${t};`;
    });
    const clientPropsType = [...serverFields, ...propsFields].join("\n");

    // useState hooks
    const hooks = (c.state?.fields ?? []).map(f => {
      const setter = toSetter(f.name);
      const generic = f.typeAnnotation ? `<${this.typeToTs(f.typeAnnotation)}>` : "";
      const init = f.defaultValue ? exprToString(f.defaultValue) : "undefined";
      return `  const [${f.name}, ${setter}] = useState${generic}(${init});`;
    });

    // client functions with state rewrites
    const fns = (c.client?.functions ?? []).map(fn =>
      this.genClientFn(fn, c.state)
    );

    // Destructure all incoming props
    const allPropNames = [
      ...(c.server?.assignments ?? []).map(a => a.name),
      ...(c.props?.fields ?? []).map(f => f.name),
    ];
    const destructure = allPropNames.length > 0
      ? `  const { ${allPropNames.join(", ")} } = props;\n`
      : "";

    // Rewrite view JSX
    const jsx = this.rewriteJsx(c.view.jsx);

    return `"use client";
// Generated by Bord v0.1 — do not edit
import { useState } from "react";

type ${c.name}ClientProps = {
${clientPropsType}
};

export function ${c.name}Client(props: ${c.name}ClientProps) {
${destructure}${hooks.join("\n")}

${fns.join("\n\n")}

  return (
    ${jsx}
  );
}
`.replace(/\n{4,}/g, "\n\n");
  }

  // ------------------------------------------------------------------ types.ts

  private genTypes(file: BordFile): string {
    const { component: c, typeAliases } = file;
    const lines: string[] = ["// Generated by Bord v0.1 — do not edit", ""];

    for (const alias of typeAliases) {
      lines.push(`export type ${alias.name} = ${this.typeToTs(alias.definition)};`);
      lines.push("");
    }

    if (c.props) {
      lines.push(`export interface ${c.name}Props {`);
      for (const f of c.props.fields) {
        const t = f.typeAnnotation ? this.typeToTs(f.typeAnnotation) : "unknown";
        const opt = f.defaultValue !== null ? "?" : "";
        lines.push(`  ${f.name}${opt}: ${t};`);
      }
      lines.push("}");
    }

    return lines.join("\n");
  }

  // ------------------------------------------------------------------ helpers

  private genClientFn(fn: ClientFunction, state: StateBlock | undefined): string {
    const asyncKw = fn.isAsync ? "async " : "";
    const params = fn.params.map(p => {
      const t = p.typeAnnotation ? `: ${this.typeToTs(p.typeAnnotation)}` : "";
      return `${p.name}${t}`;
    }).join(", ");

    let body = fn.body;

    // Rewrite state mutations → useState setters
    for (const f of state?.fields ?? []) {
      const setter = toSetter(f.name);
      body = body
        .replace(new RegExp(`state\\.${f.name}\\s*\\+=\\s*([^;\\n]+)`, "g"),
                 `${setter}(prev => prev + $1)`)
        .replace(new RegExp(`state\\.${f.name}\\s*-=\\s*([^;\\n]+)`, "g"),
                 `${setter}(prev => prev - $1)`)
        .replace(new RegExp(`state\\.${f.name}\\s*=\\s*([^;\\n]+)`, "g"),
                 `${setter}($1)`)
        .replace(new RegExp(`state\\.${f.name}`, "g"), f.name);
    }

    const indentedBody = body.split("\n").map(l => "    " + l).join("\n");
    return `  const ${fn.name} = ${asyncKw}(${params}) => {\n${indentedBody}\n  };`;
  }

  private rewriteJsx(jsx: string): string {
    return jsx
      .replace(/state\./g, "")
      .replace(/props\./g, "")
      .replace(/client\./g, "")
      .replace(/server\./g, "");
  }

  private typeToTs(type: TypeExpr): string {
    switch (type.kind) {
      case "PrimitiveType": return type.name;
      case "ArrayType":     return `${this.typeToTs(type.elementType)}[]`;
      case "OptionalType":  return `${this.typeToTs(type.innerType)} | undefined`;
      case "ReferenceType": return type.name;
      case "ObjectType": {
        const fields = type.fields.map(f => {
          const opt = f.optional ? "?" : "";
          return `${f.name}${opt}: ${this.typeToTs(f.typeAnnotation)}`;
        });
        return `{\n  ${fields.join(";\n  ")}\n}`;
      }
    }
  }
}

// ---- Standalone helpers ----

function toSetter(name: string): string {
  return `set${name.charAt(0).toUpperCase()}${name.slice(1)}`;
}

export function exprToString(expr: Expr): string {
  switch (expr.kind) {
    case "StringLiteral":  return JSON.stringify(expr.value);
    case "NumberLiteral":  return String(expr.value);
    case "BooleanLiteral": return String(expr.value);
    case "NullLiteral":    return "null";
    case "AwaitExpr":      return `await ${expr.expression}`;
    case "RawExpr":        return expr.value;
  }
}
